spring.application.name = studywithme

# H2 Datasource
spring.datasource.driver=org.h2.Driver
spring.datasource.className=jdhc:h2:mem:studywithme
spring.datasource.username=sa
spring.datasource.password=root

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console